---
title: "Curriculum Vitae"
description: |
    Qudus Uthman - Department of Crop and Soil Sciences, NCSU.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
**INTEREST**

Water, Nutrients, and Pesticides Management

Vadose zone hydrology

Environmental Soil Physics and Ecohydrology

Soil and Water Conservation and Management

System Thinking Approach

Data Analysis

Machine Learning

Artificial Intelligence

**EDUCATION**

2023 – PhD Soil, Water, and Ecosystems Sciences,
       University of Florida, Gainesville, FL. |  
       Hydrologic Sciences Concentration | 
       PhD Minor in Statistics | 
       Certificate in Biological Systems Modelling.
       
2019 – MSc Soil and Water Sciences, 
       University of Florida, Gainesville, FL.
       
2014 – B. Agric. (First Class, summa cum laude equivalent) | 
       Soil Science and Land Management, 
       Federal University of Agriculture Abeokuta, Nigeria.  


**PROFESSIONAL DEVELOPMENT AND TRAINING**

2022 – DSSAT Model International Training Program May
       16-21st 

2021 – Two-day HYDRUS short course, March 16-17th 

2018 – Teaching pedagogy and teaching with technology by
       teaching center of the University of Florida
       Graduate School


**PROFESSIONAL EXPERIENCE**

2023 – Till Date: Post Doctoral Researcher, Department of Crop and
                  Soil Sciences, North Carolina State University
                  Raleigh, NC.

2017 – 2023: Graduate assistant, Soil, Water, and
                  Ecosystem Sciences Department, Institute
                  of Food and Agricultural Sciences,
                  University of Florida, Gainesville, FL.

2016 – 2017: Federal Government of Nigeria Npower
             agricultural services program at Ogun State
             Agricultural Development Program, Abeokuta,
             Nigeria.
             
2015 – 2016: National Youth Service Corps at Ladoke Akintola
             University of Technology Ogbomosho, Nigeria.
             
2012 – 2013: Intern at Odogbolu rural community
             settlement, Community-Based Farming Scheme,
             Federal University of Agriculture, Abeokuta,
             Nigeria.
             
2011 - 2012: Intern at Organic Agriculture for Tertiary
             Institution in Nigeria, Federal University of
             Agriculture, Abeokuta, Nigeria. 

